server {
    listen 80;
    root /usr/share/nginx/html;

    location = / {
        return 301 /views/Login.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/(login|users|questions|rank|histories|categories) {
        proxy_pass http://backend-trivia:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}