services:
  trivia-api:
    image: TU_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/trivia-backend:latest
    container_name: backend-trivia
    ports:
      - "3000:3000"
    env_file: .env
    restart: always

  trivia-web:
    image: TU_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/trivia-frontend:latest
    container_name: frontend-trivia
    ports:
      - "80:80"
    depends_on:
      - trivia-api
    restart: always