name: Deploy Frontend to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'FRONTEND/**'

jobs:
  deploy-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push Frontend
        run: |
          docker build -t trivia-frontend ./FRONTEND
          docker tag trivia-frontend:latest 292177516549.dkr.ecr.us-east-1.amazonaws.com/trivia-frontend:latest
          docker push 292177516549.dkr.ecr.us-east-1.amazonaws.com/trivia-frontend:latest